### ISSUE TITLE
Error parsing response

### ISSUE THREAD

**Issue by imetallica** [Zatvobor/tirexs#269]
Hi! I'm having the following situation:

```
    Enum.map(books, fn book ->
      IO.inspect(book)
      Tirexs.HTTP.post!("/teacher/#{teacher.id}/available-book/#{book.id}", Book.to_map(book))
    end)
```

Which gives me the following error:

```
** (ArgumentError) argument error
       (jsx) src/jsx_decoder.erl:234: :jsx_decoder.value/4
     (exjsx) lib/jsx.ex:15: JSX.decode!/2
    (tirexs) lib/tirexs/http.ex:386: Tirexs.HTTP.__response__/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
```

Well, it's some kind of error trying to decode the response.

**Comment by Zatvobor** [comment]
```
iex(1)> Enum.map(books, fn book ->
...(1)>       IO.inspect(book)
...(1)>       Tirexs.HTTP.post!("/teacher/#{teacher.id}/available-book/#{book.id}", Book.to_map(book))
...(1)>     end)
** (CompileError) iex:1: undefined function books/0
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
iex(1)>
```

so, i can't reproduce.
